### ISSUE TITLE
Show Tezos symbol next to all amounts

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Tezos-Wallet#176]
It is not completely clear where in the wallet users are supposed to enter amounts in tez vs. utez (one millionth of a tez). All amount entries are actually supposed to be in tez. To make this clear, let us put the Tezos symbol next to all amounts. 

This will affect the following screens:
Sending 
Delegating
Creating a new delegated address

In all three cases, the symbol should be show next to both the amount and fee.

**Comment by vishakh** [comment]
@polinasoshkina Tagging you in case you want to add any design to this.

**Comment by Tomcatus** [comment]
@vishakh just to be sure - this is not only adding the tez icon but also changing the actual logic of the app to display everything in tez? Because e.g. in the add delegate modal the conversion is made on purpose, and we display utez there without the symbol. According to this task you want to change that to display value in tez and add the Tezos symbol after the amount?

**Comment by vishakh** [comment]
@Tomcatus Nope, it's only adding a tez icon, that's all.

**Comment by umurb** [comment]
TZ symbol is now visible next to all amounts, including custom fees. Closing this ticket
